name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - zeekurity/zeek
          - zeekurity/zeek-dev
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y cmake g++ libpcap-dev
      - name: Install
        env:
          PATH: /usr/local/bin:/opt/cmake/bin:/opt/spicy/bin:/opt/zeek/bin:/opt/zeek/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
          git config --global --add safe.directory $PWD
          git clean -fd
          eval $(zkg env)
          zkg -vvvvv install --force .

      - name: Show logs
        if: always()
        run: |
          tail -n 1000000 $(zkg config state_dir)/logs/*.log $(zkg config state_dir)/testing/*/clones/*/zkg.*.stderr || true
